package com.dlsc.jfxcentral2.utils;

import javafx.scene.Node;

/**
 * The MobileResponse class represents the response generated by a mobile route.
 * It encapsulates the details of the requested URL, the view to be displayed,
 * and any potential redirection path.
 */
public class MobileResponse {

    /**
     * The view to be displayed.
     */
    private final Node view;

    /**
     * The original request URL.
     */
    private final String requestUrl;

    /**
     * The path to redirect to, if any.
     */
    private final String redirectPath;

    /**
     * The final URL after all redirections have been resolved.
     */
    private String finalUrl;

    /**
     * Private constructor to initialize a MobileResponse instance.
     *
     * @param requestUrl   the original request URL
     * @param view         the view to be displayed
     * @param redirectPath the path to redirect to, if any
     */
    private MobileResponse(String requestUrl, Node view, String redirectPath) {
        this.requestUrl = requestUrl;
        this.view = view;
        this.redirectPath = redirectPath;
    }

    /**
     * Creates a MobileResponse instance representing a view response.
     *
     * @param requestUrl the original request URL
     * @param view       the view to be displayed
     * @return a new MobileResponse instance
     */
    public static MobileResponse view(String requestUrl, Node view) {
        return new MobileResponse(requestUrl, view, null);
    }

    /**
     * Creates a MobileResponse instance representing a redirect response.
     *
     * @param requestUrl   the original request URL
     * @param redirectPath the path to redirect to
     * @return a new MobileResponse instance
     */
    public static MobileResponse redirect(String requestUrl, String redirectPath) {
        return new MobileResponse(requestUrl, null, redirectPath);
    }

    public String getRequestUrl() {
        return requestUrl;
    }

    public Node getView() {
        return view;
    }

    public String getRedirectPath() {
        return redirectPath;
    }

    public String getFinalUrl() {
        return finalUrl;
    }

    public void setFinalUrl(String finalUrl) {
        this.finalUrl = finalUrl;
    }
}
